# Generated by Django 2.1.7 on 2020-07-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0010_ffoodtypes_ggoods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FFoodTypes',
            new_name='FoodTypes',
        ),
        migrations.RenameModel(
            old_name='GGoods',
            new_name='Goods',
        ),
    ]
